# Generated by Django 6.0.4 on 2026-04-10 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='lectures_per_week',
            field=models.PositiveIntegerField(default=3, help_text='Number of lectures per week (for scheduling)'),
        ),
        migrations.AddField(
            model_name='subjectassignment',
            name='lectures_per_week',
            field=models.PositiveIntegerField(default=3, help_text='Number of lectures for this subject in this class per week'),
        ),
        migrations.AddField(
            model_name='timetable',
            name='allow_same_subject_consecutive',
            field=models.BooleanField(default=False, help_text='Allow same subject in consecutive slots'),
        ),
        migrations.AddField(
            model_name='timetable',
            name='max_consecutive_lectures',
            field=models.PositiveIntegerField(default=3, help_text='Maximum consecutive lectures before break'),
        ),
        migrations.AddField(
            model_name='timetable',
            name='max_labs_per_day',
            field=models.PositiveIntegerField(default=1, help_text='Maximum lab sessions per day per class'),
        ),
    ]
