# Generated by Django 6.0.4 on 2026-04-10 20:07

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0002_subject_lectures_per_week_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='timetable',
            name='max_labs_per_day',
        ),
        migrations.AddField(
            model_name='classroom',
            name='floor',
            field=models.CharField(blank=True, help_text="Floor number (e.g., '1st', '2nd', 'Ground')", max_length=10),
        ),
        migrations.AddField(
            model_name='subject',
            name='has_lab_component',
            field=models.BooleanField(default=False, help_text='Whether this subject has a lab component'),
        ),
        migrations.AddField(
            model_name='timetable',
            name='break_after_slot',
            field=models.PositiveIntegerField(default=3, help_text='Break inserted after this slot number'),
        ),
        migrations.AddField(
            model_name='timetable',
            name='break_duration',
            field=models.PositiveIntegerField(default=30, help_text='Break duration in minutes'),
        ),
        migrations.AddField(
            model_name='timetable',
            name='lab_duration',
            field=models.PositiveIntegerField(default=120, help_text='Lab duration in minutes'),
        ),
        migrations.AddField(
            model_name='timetable',
            name='labs_per_week',
            field=models.PositiveIntegerField(default=1, help_text='Total labs per week (≤ 5)', validators=[django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AddField(
            model_name='timetable',
            name='lecture_duration',
            field=models.PositiveIntegerField(default=60, help_text='Lecture duration in minutes'),
        ),
        migrations.AddField(
            model_name='timetable',
            name='start_time',
            field=models.TimeField(default='09:00', help_text='Daily start time'),
        ),
        migrations.AlterField(
            model_name='classroom',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
