# Generated by Django 4.2.30 on 2026-04-11 03:03

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('notification_type', models.CharField(choices=[('ANNOUNCEMENT', 'Announcement'), ('ALERT', 'Alert'), ('ASSIGNMENT', 'Assignment'), ('FEE', 'Fee')], default='ANNOUNCEMENT', max_length=20)),
                ('target_role', models.CharField(blank=True, max_length=20, null=True)),
                ('target_year', models.IntegerField(blank=True, null=True)),
                ('is_global', models.BooleanField(default=False)),
                ('metadata', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sender', models.ForeignKey(blank=True, db_column='sender_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.profile')),
                ('target_department', models.ForeignKey(blank=True, db_column='target_department_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.department')),
            ],
            options={
                'db_table': 'notifications',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='UserNotification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_read', models.BooleanField(default=False)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('notification', models.ForeignKey(db_column='notification_id', on_delete=django.db.models.deletion.CASCADE, to='notifications.notification')),
                ('user', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, to='accounts.profile')),
            ],
            options={
                'db_table': 'user_notifications',
                'managed': True,
            },
        ),
    ]
