# Generated by Django 4.2.30 on 2026-04-11 02:40

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('gymkhana', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('category', models.CharField(blank=True, max_length=100, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'sports',
                'managed': False,
            },
        ),
        migrations.AlterModelOptions(
            name='equipment',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='equipmentbooking',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='turf',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='turfbooking',
            options={'managed': False},
        ),
    ]
