# Generated by Django 4.2.30 on 2026-04-11 02:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gymkhana', '0002_sport_alter_equipment_options_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='equipment',
            table='equipment',
        ),
        migrations.AlterModelTable(
            name='equipmentbooking',
            table='equipment_bookings',
        ),
        migrations.AlterModelTable(
            name='turf',
            table='turfs',
        ),
        migrations.AlterModelTable(
            name='turfbooking',
            table='turf_bookings',
        ),
    ]
