# Generated by Django 4.2.30 on 2026-04-11 02:40

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('lost_found', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LostFoundItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('item_type', models.CharField(choices=[('LOST', 'Lost'), ('FOUND', 'Found')], max_length=10)),
                ('reporter_name', models.CharField(max_length=255)),
                ('roll_number', models.CharField(blank=True, max_length=50, null=True)),
                ('department', models.CharField(blank=True, max_length=100, null=True)),
                ('item_name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('location', models.CharField(max_length=255)),
                ('item_date', models.DateField()),
                ('contact', models.CharField(blank=True, max_length=20, null=True)),
                ('image_url', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('RESOLVED', 'Resolved'), ('CLOSED', 'Closed')], default='OPEN', max_length=20)),
                ('admin_verified', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'lost_found_items',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='Item',
        ),
        migrations.AlterModelOptions(
            name='claim',
            options={'managed': False},
        ),
        migrations.AlterField(
            model_name='claim',
            name='item',
            field=models.ForeignKey(db_column='item_id', on_delete=models.deletion.CASCADE, related_name='claims', to='lost_found.lostfounditem'),
        ),
    ]
