# Generated by Django 4.2.30 on 2026-04-11 02:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lost_found', '0002_lostfounditem_delete_item_alter_claim_options'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='claim',
            table='claims',
        ),
    ]
